let date=new Date()
console.log(date)
let year=date.getFullYear()
console.log(year)
let month=date.getMonth()
console.log(month)
let localdate=date.toLocaleDateString()
console.log(localdate)
let day=date.getDay()
console.log(day)
let utcday=date.getUTCDay()
console.log(utcday)
let offset=date.getTimezoneOffset()
console.log(offset)
let localtime=date.toLocaleTimeString()
console.log(localtime)